spring.data.mongodb.uri=mongodb://127.0.0.1:27017/?readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false
spring.data.mongodb.database=demo
spring.data.mongodb.auto-index-creation = true

